apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-cm
  labels:
    mariadb: cm
data:
  70-primary.cnf: |
    [mariadb]
    log-bin
    log-basename=primary0
    binlog-format=mixed
    port=3306
    bind-address=0.0.0.0
  70-replica.cnf: |
    [mariadb]
    port=3306
