apiVersion: v1
kind: Service
metadata:
  labels:
    mariadb: svc
  name: mariadb-svc
spec:
  clusterIP: None
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    mariadb: ss
---
apiVersion: v1
kind: Service
metadata:
  labels:
    mariadb: svc
  name: mariadb-read-svc
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    mariadb: ss
  type: ClusterIP
